#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebRepuestos")]
public partial class RepuestosModelDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  #endregion
	
	public RepuestosModelDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebRepuestosConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public RepuestosModelDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public RepuestosModelDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public RepuestosModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public RepuestosModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<t_Envios> t_Envios
	{
		get
		{
			return this.GetTable<t_Envios>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_plazos_importacion")]
	public ISingleResult<webr_obtiene_plazos_importacionResult> webr_obtiene_plazos_importacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_identificador, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<webr_obtiene_plazos_importacionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_modifica_plazos_importacion")]
	public int webr_modifica_plazos_importacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string courier, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string aereo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string maritimo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string terrestre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_envio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string nom_Centro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string nom_proo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string rut_usr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courier, aereo, maritimo, terrestre, id_envio, nom_Centro, nom_proo, rut_usr, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(8)));
		o_msg_error = ((string)(result.GetParameterValue(9)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_validez_cotizacion")]
	public ISingleResult<webr_obtiene_validez_cotizacionResult> webr_obtiene_validez_cotizacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(0)));
		o_msg_error = ((string)(result.GetParameterValue(1)));
		return ((ISingleResult<webr_obtiene_validez_cotizacionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_actualiza_validez_cotizacion")]
	public int webr_actualiza_validez_cotizacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dias, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, dias, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_plazo_envio")]
	public ISingleResult<webr_obtiene_plazo_envioResult> webr_obtiene_plazo_envio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_tipo_transporte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_marca, i_tipo_transporte, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((ISingleResult<webr_obtiene_plazo_envioResult>)(result.ReturnValue));
	}
    // REQ - Cotizaciones Automaticas Marzo 2022
    //[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_modifica_plazos_importacion_v2")]
    //public int webr_modifica_plazos_importacion_v2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_envio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string i_valor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
    //{
    //	IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_envio, i_valor, o_nro_error, o_msg_error);
    //	o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
    //	o_msg_error = ((string)(result.GetParameterValue(3)));
    //	return ((int)(result.ReturnValue));
    //}
    [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.webr_modifica_plazos_importacion_v2")]
    public int webr_modifica_plazos_importacion_v2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> id_envio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(10)")] string i_valor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "varchar(10)")] string i_fci, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string o_msg_error)
    {
        IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_envio, i_valor, i_fci.Replace(",","."), o_nro_error, o_msg_error);
        o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(3)));
        o_msg_error = ((string)(result.GetParameterValue(4)));
        return ((int)(result.ReturnValue));
    }
    // REQ - Cotizaciones Automaticas Marzo 2022


    [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_actualiza_tipo_transporte")]
	public int webr_actualiza_tipo_transporte([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> i_habilitado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_habilitado, i_id, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_tipo_transporte")]
	public ISingleResult<webr_obtiene_tipo_transporteResult> webr_obtiene_tipo_transporte([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_ref, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_ref, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<webr_obtiene_tipo_transporteResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_elimina_tipo_transporte")]
	public int webr_elimina_tipo_transporte([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_id, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_inserta_tipo_transporte")]
	public int webr_inserta_tipo_transporte([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_nombre, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_plazos_importacion_v2")]
	public ISingleResult<webr_obtiene_plazos_importacion_v2Result> webr_obtiene_plazos_importacion_v2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_marca, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<webr_obtiene_plazos_importacion_v2Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_datos_pdf_edita")]
	public ISingleResult<webr_datos_pdf_editaResult> webr_datos_pdf_edita([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_usr_rut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_codRep, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_vin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_fecha_desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_fecha_hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_userStr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_num_soli, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_usr_rut, i_marca, i_codRep, i_vin, i_fecha_desde, i_fecha_hasta, i_userStr, i_num_soli, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(8)));
		o_msg_error = ((string)(result.GetParameterValue(9)));
		return ((ISingleResult<webr_datos_pdf_editaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_motivo_pedidos")]
	public ISingleResult<webr_obtiene_motivo_pedidosResult> webr_obtiene_motivo_pedidos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_ref, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_ref, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<webr_obtiene_motivo_pedidosResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_elimina_motivo_pedido")]
	public int webr_elimina_motivo_pedido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_id, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_actualiza_motivo_pedido_habilitado")]
	public int webr_actualiza_motivo_pedido_habilitado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> i_habilitado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_habilitado, i_id, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((int)(result.ReturnValue));
	}

    [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.webr_actualiza_motivo_pedido_documentacion")]
    public int webr_actualiza_motivo_pedido_documentacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> i_habilitado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(10)")] string i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string o_msg_error)
    {
        IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_habilitado, i_id, o_nro_error, o_msg_error);
        o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
        o_msg_error = ((string)(result.GetParameterValue(3)));
        return ((int)(result.ReturnValue));
    }
    [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.webr_actualiza_motivo_pedido_informacioAdicional")]
    public int webr_actualiza_motivo_pedido_informacioAdicional([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> i_habilitado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(10)")] string i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string o_msg_error)
    {
        IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_habilitado, i_id, o_nro_error, o_msg_error);
        o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
        o_msg_error = ((string)(result.GetParameterValue(3)));
        return ((int)(result.ReturnValue));
    }

    [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_modifica_bloqueo_motivo_pedido")]
	public int webr_modifica_bloqueo_motivo_pedido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_reg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string i_valor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_reg, i_valor, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_inserta_motivo_pedido")]
	public int webr_inserta_motivo_pedido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string i_codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string i_bloqueo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_descripcion, i_codigo, i_marca, i_bloqueo, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(4)));
		o_msg_error = ((string)(result.GetParameterValue(5)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_motivo_pedido_sol")]
	public ISingleResult<webr_obtiene_motivo_pedido_solResult> webr_obtiene_motivo_pedido_sol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string i_nombre_motivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_nombre_motivo, i_marca, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((ISingleResult<webr_obtiene_motivo_pedido_solResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_tipo_motivodr")]
	public ISingleResult<webr_obtiene_tipo_motivodrResult> webr_obtiene_tipo_motivodr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(0)));
		o_msg_error = ((string)(result.GetParameterValue(1)));
		return ((ISingleResult<webr_obtiene_tipo_motivodrResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_motivos_dr")]
	public ISingleResult<webr_obtiene_motivos_drResult> webr_obtiene_motivos_dr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(0)));
		o_msg_error = ((string)(result.GetParameterValue(1)));
		return ((ISingleResult<webr_obtiene_motivos_drResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_elimina_motivo_dr")]
	public int webr_elimina_motivo_dr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_id, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_actualiza_motivo_dr")]
	public int webr_actualiza_motivo_dr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string i_paridad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_paridad, i_id, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(2)));
		o_msg_error = ((string)(result.GetParameterValue(3)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_agrega_motivo_dr")]
	public int webr_agrega_motivo_dr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string i_paridad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string i_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_cod_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_paridad, i_descripcion, i_tipo, o_cod_error, o_msg_error);
		o_cod_error = ((System.Nullable<int>)(result.GetParameterValue(3)));
		o_msg_error = ((string)(result.GetParameterValue(4)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_get_parametro_sistema")]
	public ISingleResult<sp_get_parametro_sistemaResult> sp_get_parametro_sistema([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_key, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_key, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<sp_get_parametro_sistemaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_cotizacion_v2")]
	public ISingleResult<webr_obtiene_cotizacion_v2Result> webr_obtiene_cotizacion_v2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string i_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_nro_solicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_fecha_desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_fecha_hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_cod_repuesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_vin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string i_estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string i_concesionario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(350)")] string i_local, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_identificador, i_usuario, i_marca, i_nro_solicitud, i_fecha_desde, i_fecha_hasta, i_cod_repuesto, i_vin, i_estado, i_concesionario, i_local, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(11)));
		o_msg_error = ((string)(result.GetParameterValue(12)));
		return ((ISingleResult<webr_obtiene_cotizacion_v2Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_detalle_Cotizacion")]
	public ISingleResult<webr_obtiene_detalle_CotizacionResult> webr_obtiene_detalle_Cotizacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_id_solicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_id_solicitud, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<webr_obtiene_detalle_CotizacionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_obtiene_cotizacion_consulta")]
	public ISingleResult<webr_obtiene_cotizacion_consultaResult> webr_obtiene_cotizacion_consulta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string i_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_nro_solicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_fecha_desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_fecha_hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_cod_repuesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string i_vin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string i_estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string i_concesionario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(350)")] string i_local, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_identificador, i_usuario, i_marca, i_nro_solicitud, i_fecha_desde, i_fecha_hasta, i_cod_repuesto, i_vin, i_estado, i_concesionario, i_local, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(11)));
		o_msg_error = ((string)(result.GetParameterValue(12)));
		return ((ISingleResult<webr_obtiene_cotizacion_consultaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webr_valida_estado_cotizacion")]
	public ISingleResult<webr_valida_estado_cotizacionResult> webr_valida_estado_cotizacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_id_cotizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> o_nro_error, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string o_msg_error)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_id_cotizacion, o_nro_error, o_msg_error);
		o_nro_error = ((System.Nullable<int>)(result.GetParameterValue(1)));
		o_msg_error = ((string)(result.GetParameterValue(2)));
		return ((ISingleResult<webr_valida_estado_cotizacionResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Envios")]
public partial class t_Envios
{
	
	private int _id_envio;
	
	private string _nom_Centro;
	
	private string _nom_proo;
	
	private string _courier;
	
	private string _aereo;
	
	private string _maritimo;
	
	private string _terrestre;
	
	public t_Envios()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_envio", DbType="Int NOT NULL")]
	public int id_envio
	{
		get
		{
			return this._id_envio;
		}
		set
		{
			if ((this._id_envio != value))
			{
				this._id_envio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_Centro", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string nom_Centro
	{
		get
		{
			return this._nom_Centro;
		}
		set
		{
			if ((this._nom_Centro != value))
			{
				this._nom_Centro = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_proo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string nom_proo
	{
		get
		{
			return this._nom_proo;
		}
		set
		{
			if ((this._nom_proo != value))
			{
				this._nom_proo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courier", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string courier
	{
		get
		{
			return this._courier;
		}
		set
		{
			if ((this._courier != value))
			{
				this._courier = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aereo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string aereo
	{
		get
		{
			return this._aereo;
		}
		set
		{
			if ((this._aereo != value))
			{
				this._aereo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritimo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string maritimo
	{
		get
		{
			return this._maritimo;
		}
		set
		{
			if ((this._maritimo != value))
			{
				this._maritimo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terrestre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string terrestre
	{
		get
		{
			return this._terrestre;
		}
		set
		{
			if ((this._terrestre != value))
			{
				this._terrestre = value;
			}
		}
	}
}

public partial class webr_obtiene_plazos_importacionResult
{
	
	private int _id_envio;
	
	private string _nom_Centro;
	
	private string _nom_proo;
	
	private string _courier;
	
	private string _aereo;
	
	private string _maritimo;
	
	private string _terrestre;
	
	public webr_obtiene_plazos_importacionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_envio", DbType="Int NOT NULL")]
	public int id_envio
	{
		get
		{
			return this._id_envio;
		}
		set
		{
			if ((this._id_envio != value))
			{
				this._id_envio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_Centro", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string nom_Centro
	{
		get
		{
			return this._nom_Centro;
		}
		set
		{
			if ((this._nom_Centro != value))
			{
				this._nom_Centro = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_proo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string nom_proo
	{
		get
		{
			return this._nom_proo;
		}
		set
		{
			if ((this._nom_proo != value))
			{
				this._nom_proo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courier", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string courier
	{
		get
		{
			return this._courier;
		}
		set
		{
			if ((this._courier != value))
			{
				this._courier = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aereo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string aereo
	{
		get
		{
			return this._aereo;
		}
		set
		{
			if ((this._aereo != value))
			{
				this._aereo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritimo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string maritimo
	{
		get
		{
			return this._maritimo;
		}
		set
		{
			if ((this._maritimo != value))
			{
				this._maritimo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terrestre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string terrestre
	{
		get
		{
			return this._terrestre;
		}
		set
		{
			if ((this._terrestre != value))
			{
				this._terrestre = value;
			}
		}
	}
}

public partial class webr_obtiene_validez_cotizacionResult
{
	
	private int _id;
	
	private string _nombre;
	
	private int _dias;
	
	public webr_obtiene_validez_cotizacionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this._nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias", DbType="Int NOT NULL")]
	public int dias
	{
		get
		{
			return this._dias;
		}
		set
		{
			if ((this._dias != value))
			{
				this._dias = value;
			}
		}
	}
}

public partial class webr_obtiene_plazo_envioResult
{
	
	private string _Dias;
	
	private string _Nombre;
	
	public webr_obtiene_plazo_envioResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Dias
	{
		get
		{
			return this._Dias;
		}
		set
		{
			if ((this._Dias != value))
			{
				this._Dias = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
}

public partial class webr_obtiene_tipo_transporteResult
{
	
	private int _Id;
	
	private string _Nombre;
	
	private bool _Habilitado;
	
	public webr_obtiene_tipo_transporteResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habilitado", DbType="Bit NOT NULL")]
	public bool Habilitado
	{
		get
		{
			return this._Habilitado;
		}
		set
		{
			if ((this._Habilitado != value))
			{
				this._Habilitado = value;
			}
		}
	}
}

public partial class webr_obtiene_plazos_importacion_v2Result
{
	
	private int _Id;
	
	private string _Marca;
	
	private string _Nombre;
	
	private string _Dias;

    private decimal _Fci;

    public webr_obtiene_plazos_importacion_v2Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Marca
	{
		get
		{
			return this._Marca;
		}
		set
		{
			if ((this._Marca != value))
			{
				this._Marca = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Dias
	{
		get
		{
			return this._Dias;
		}
		set
		{
			if ((this._Dias != value))
			{
				this._Dias = value;
			}
		}
	}
    //REQ - Cotizaciones Automaticas Marzo 2022
    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Fci", DbType = "Decimal(11,2) NOT NULL", CanBeNull = false)]
    public decimal Fci
    {
        get
        {
            return this._Fci;
        }
        set
        {
            if ((this._Fci != value))
            {
                this._Fci = value;
            }
        }
    }
    //REQ - Cotizaciones Automaticas Marzo 2022

}

public partial class webr_datos_pdf_editaResult
{
	
	private int _numeroSolicitud;
	
	private System.DateTime _fecha;
	
	private string _marca;
	
	private string _codRepto;
	
	private string _descripcion;
	
	private int _cantidad;
	
	private string _usuario;
	
	private string _concesionario;
	
	private string _precio_Solicitud;
	
	private string _tipo;
	
	private string _vin;
	
	private string _envio;
	
	private string _sesion;
	
	private string _dias;
	
	private string _Estado;
	
	private System.Nullable<decimal> _PrecioUnitario;
	
	private string _Comentario;
	
	private System.Nullable<bool> _anulada;
	
	private string _motivo;
	
	public webr_datos_pdf_editaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroSolicitud", DbType="Int NOT NULL")]
	public int numeroSolicitud
	{
		get
		{
			return this._numeroSolicitud;
		}
		set
		{
			if ((this._numeroSolicitud != value))
			{
				this._numeroSolicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
	public System.DateTime fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this._fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this._marca = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRepto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string codRepto
	{
		get
		{
			return this._codRepto;
		}
		set
		{
			if ((this._codRepto != value))
			{
				this._codRepto = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this._descripcion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
	public int cantidad
	{
		get
		{
			return this._cantidad;
		}
		set
		{
			if ((this._cantidad != value))
			{
				this._cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this._usuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concesionario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string concesionario
	{
		get
		{
			return this._concesionario;
		}
		set
		{
			if ((this._concesionario != value))
			{
				this._concesionario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_Solicitud", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string precio_Solicitud
	{
		get
		{
			return this._precio_Solicitud;
		}
		set
		{
			if ((this._precio_Solicitud != value))
			{
				this._precio_Solicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string tipo
	{
		get
		{
			return this._tipo;
		}
		set
		{
			if ((this._tipo != value))
			{
				this._tipo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vin", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string vin
	{
		get
		{
			return this._vin;
		}
		set
		{
			if ((this._vin != value))
			{
				this._vin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string envio
	{
		get
		{
			return this._envio;
		}
		set
		{
			if ((this._envio != value))
			{
				this._envio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string sesion
	{
		get
		{
			return this._sesion;
		}
		set
		{
			if ((this._sesion != value))
			{
				this._sesion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias", DbType="VarChar(10)")]
	public string dias
	{
		get
		{
			return this._dias;
		}
		set
		{
			if ((this._dias != value))
			{
				this._dias = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(5)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnitario", DbType="Decimal(20,4)")]
	public System.Nullable<decimal> PrecioUnitario
	{
		get
		{
			return this._PrecioUnitario;
		}
		set
		{
			if ((this._PrecioUnitario != value))
			{
				this._PrecioUnitario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(200)")]
	public string Comentario
	{
		get
		{
			return this._Comentario;
		}
		set
		{
			if ((this._Comentario != value))
			{
				this._Comentario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anulada", DbType="Bit")]
	public System.Nullable<bool> anulada
	{
		get
		{
			return this._anulada;
		}
		set
		{
			if ((this._anulada != value))
			{
				this._anulada = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="VarChar(50)")]
	public string motivo
	{
		get
		{
			return this._motivo;
		}
		set
		{
			if ((this._motivo != value))
			{
				this._motivo = value;
			}
		}
	}
}

public partial class webr_obtiene_motivo_pedidosResult
{
	
	private int _ID_Motivo_pedido;
	
	private string _mp_Marca;
	
	private string _MP_Bloqueo;
	
	private string _MP_Descripcion;
	
	private int _MP_Flag;
	
	private string _MP_codigo;

    private int _mp_documentacion;

    private int _mp_informacion;

    public webr_obtiene_motivo_pedidosResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motivo_pedido", DbType="Int NOT NULL")]
	public int ID_Motivo_pedido
	{
		get
		{
			return this._ID_Motivo_pedido;
		}
		set
		{
			if ((this._ID_Motivo_pedido != value))
			{
				this._ID_Motivo_pedido = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mp_Marca", DbType="VarChar(1000)")]
	public string mp_Marca
	{
		get
		{
			return this._mp_Marca;
		}
		set
		{
			if ((this._mp_Marca != value))
			{
				this._mp_Marca = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MP_Bloqueo", DbType="VarChar(2)")]
	public string MP_Bloqueo
	{
		get
		{
			return this._MP_Bloqueo;
		}
		set
		{
			if ((this._MP_Bloqueo != value))
			{
				this._MP_Bloqueo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MP_Descripcion", DbType="NChar(100) NOT NULL", CanBeNull=false)]
	public string MP_Descripcion
	{
		get
		{
			return this._MP_Descripcion;
		}
		set
		{
			if ((this._MP_Descripcion != value))
			{
				this._MP_Descripcion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MP_Flag", DbType="Int NOT NULL")]
	public int MP_Flag
	{
		get
		{
			return this._MP_Flag;
		}
		set
		{
			if ((this._MP_Flag != value))
			{
				this._MP_Flag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MP_codigo", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string MP_codigo
	{
		get
		{
			return this._MP_codigo;
		}
		set
		{
			if ((this._MP_codigo != value))
			{
				this._MP_codigo = value;
			}
		}
	}

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_mp_documentacion", DbType = "Int NOT NULL")]
    public int mp_documentacion
    {
        get
        {
            return this._mp_documentacion;
        }
        set
        {
            if ((this._mp_documentacion != value))
            {
                this._mp_documentacion = value;
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_mp_informacion", DbType = "Int NOT NULL")]
    public int mp_informacion
    {
        get
        {
            return this._mp_informacion;
        }
        set
        {
            if ((this._mp_informacion != value))
            {
                this._mp_informacion = value;
            }
        }
    }

}

public partial class webr_obtiene_motivo_pedido_solResult
{
	
	private int _ID;
	
	private string _NOMBRE;
	
	private string _BLOQUEO;
	
	private string _CODIGO;
	
	private int _HABILITADO;
	
	public webr_obtiene_motivo_pedido_solResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NChar(100) NOT NULL", CanBeNull=false)]
	public string NOMBRE
	{
		get
		{
			return this._NOMBRE;
		}
		set
		{
			if ((this._NOMBRE != value))
			{
				this._NOMBRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOQUEO", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
	public string BLOQUEO
	{
		get
		{
			return this._BLOQUEO;
		}
		set
		{
			if ((this._BLOQUEO != value))
			{
				this._BLOQUEO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string CODIGO
	{
		get
		{
			return this._CODIGO;
		}
		set
		{
			if ((this._CODIGO != value))
			{
				this._CODIGO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABILITADO", DbType="Int NOT NULL")]
	public int HABILITADO
	{
		get
		{
			return this._HABILITADO;
		}
		set
		{
			if ((this._HABILITADO != value))
			{
				this._HABILITADO = value;
			}
		}
	}
}

public partial class webr_obtiene_tipo_motivodrResult
{
	
	private int _Id;
	
	private string _Nombre;
	
	public webr_obtiene_tipo_motivodrResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
}

public partial class webr_obtiene_motivos_drResult
{
	
	private int _ID;
	
	private string _DESCRIPCION;
	
	private string _TIPO_MOTIVO;
	
	private System.Nullable<int> _PARIDAD;
	
	public webr_obtiene_motivos_drResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(100)")]
	public string DESCRIPCION
	{
		get
		{
			return this._DESCRIPCION;
		}
		set
		{
			if ((this._DESCRIPCION != value))
			{
				this._DESCRIPCION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_MOTIVO", DbType="VarChar(50)")]
	public string TIPO_MOTIVO
	{
		get
		{
			return this._TIPO_MOTIVO;
		}
		set
		{
			if ((this._TIPO_MOTIVO != value))
			{
				this._TIPO_MOTIVO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARIDAD", DbType="Int")]
	public System.Nullable<int> PARIDAD
	{
		get
		{
			return this._PARIDAD;
		}
		set
		{
			if ((this._PARIDAD != value))
			{
				this._PARIDAD = value;
			}
		}
	}
}

public partial class sp_get_parametro_sistemaResult
{
	
	private string _Valor;
	
	public sp_get_parametro_sistemaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Valor
	{
		get
		{
			return this._Valor;
		}
		set
		{
			if ((this._Valor != value))
			{
				this._Valor = value;
			}
		}
	}
}

public partial class webr_obtiene_cotizacion_v2Result
{
	
	private System.Nullable<long> _Fila;
	
	private int _numeroSolicitud;
	
	private string _fecha;
	
	private string _marca;
	
	private string _codRepto;
	
	private string _descripcion;
	
	private int _cantidad;
	
	private string _Concesionario;
	
	private string _precio_solicitud;
	
	private string _tipo;
	
	private string _vin;
	
	private string _envio;
	
	private string _sesion;
	
	private string _Dias;
	
	private string _Estado;
	
	public webr_obtiene_cotizacion_v2Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fila", DbType="BigInt")]
	public System.Nullable<long> Fila
	{
		get
		{
			return this._Fila;
		}
		set
		{
			if ((this._Fila != value))
			{
				this._Fila = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroSolicitud", DbType="Int NOT NULL")]
	public int numeroSolicitud
	{
		get
		{
			return this._numeroSolicitud;
		}
		set
		{
			if ((this._numeroSolicitud != value))
			{
				this._numeroSolicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="VarChar(30)")]
	public string fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this._fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this._marca = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRepto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string codRepto
	{
		get
		{
			return this._codRepto;
		}
		set
		{
			if ((this._codRepto != value))
			{
				this._codRepto = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this._descripcion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
	public int cantidad
	{
		get
		{
			return this._cantidad;
		}
		set
		{
			if ((this._cantidad != value))
			{
				this._cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concesionario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Concesionario
	{
		get
		{
			return this._Concesionario;
		}
		set
		{
			if ((this._Concesionario != value))
			{
				this._Concesionario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_solicitud", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string precio_solicitud
	{
		get
		{
			return this._precio_solicitud;
		}
		set
		{
			if ((this._precio_solicitud != value))
			{
				this._precio_solicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string tipo
	{
		get
		{
			return this._tipo;
		}
		set
		{
			if ((this._tipo != value))
			{
				this._tipo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vin", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string vin
	{
		get
		{
			return this._vin;
		}
		set
		{
			if ((this._vin != value))
			{
				this._vin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string envio
	{
		get
		{
			return this._envio;
		}
		set
		{
			if ((this._envio != value))
			{
				this._envio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string sesion
	{
		get
		{
			return this._sesion;
		}
		set
		{
			if ((this._sesion != value))
			{
				this._sesion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Dias
	{
		get
		{
			return this._Dias;
		}
		set
		{
			if ((this._Dias != value))
			{
				this._Dias = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(5)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
}

public partial class webr_obtiene_detalle_CotizacionResult
{
	
	private int _id_cotizacion;
	
	private System.Nullable<int> _numeroSolicitud;
	
	private System.Nullable<System.DateTime> _fecha;
	
	private string _marca;
	
	private string _codRepto;
	
	private string _descripcion;
	
	private System.Nullable<int> _cantidad;
	
	private string _usuario;
	
	private string _concesionario;
	
	private string _precio_Solicitud;
	
	private string _tipo;
	
	private string _vin;
	
	private string _envio;
	
	private string _sesion;
	
	private string _dias;
	
	private string _Estado;
	
	private System.Nullable<decimal> _PrecioUnitario;
	
	private string _Comentario;
	
	private System.Nullable<bool> _anulada;
	
	private string _motivo;
	
	private System.Nullable<bool> _confirmada;
	
	private System.Nullable<bool> _tipo_vfc;
	
	private System.Nullable<int> _criticidad;
	
	private string _obs_criticidad;
	
	public webr_obtiene_detalle_CotizacionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cotizacion", DbType="Int NOT NULL")]
	public int id_cotizacion
	{
		get
		{
			return this._id_cotizacion;
		}
		set
		{
			if ((this._id_cotizacion != value))
			{
				this._id_cotizacion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroSolicitud", DbType="Int")]
	public System.Nullable<int> numeroSolicitud
	{
		get
		{
			return this._numeroSolicitud;
		}
		set
		{
			if ((this._numeroSolicitud != value))
			{
				this._numeroSolicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
	public System.Nullable<System.DateTime> fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this._fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(15)")]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this._marca = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRepto", DbType="VarChar(50)")]
	public string codRepto
	{
		get
		{
			return this._codRepto;
		}
		set
		{
			if ((this._codRepto != value))
			{
				this._codRepto = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250)")]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this._descripcion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
	public System.Nullable<int> cantidad
	{
		get
		{
			return this._cantidad;
		}
		set
		{
			if ((this._cantidad != value))
			{
				this._cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(100)")]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this._usuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concesionario", DbType="VarChar(50)")]
	public string concesionario
	{
		get
		{
			return this._concesionario;
		}
		set
		{
			if ((this._concesionario != value))
			{
				this._concesionario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_Solicitud", DbType="VarChar(100)")]
	public string precio_Solicitud
	{
		get
		{
			return this._precio_Solicitud;
		}
		set
		{
			if ((this._precio_Solicitud != value))
			{
				this._precio_Solicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(100)")]
	public string tipo
	{
		get
		{
			return this._tipo;
		}
		set
		{
			if ((this._tipo != value))
			{
				this._tipo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vin", DbType="VarChar(20)")]
	public string vin
	{
		get
		{
			return this._vin;
		}
		set
		{
			if ((this._vin != value))
			{
				this._vin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio", DbType="VarChar(50)")]
	public string envio
	{
		get
		{
			return this._envio;
		}
		set
		{
			if ((this._envio != value))
			{
				this._envio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesion", DbType="VarChar(250)")]
	public string sesion
	{
		get
		{
			return this._sesion;
		}
		set
		{
			if ((this._sesion != value))
			{
				this._sesion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias", DbType="VarChar(10)")]
	public string dias
	{
		get
		{
			return this._dias;
		}
		set
		{
			if ((this._dias != value))
			{
				this._dias = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(5)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnitario", DbType="Decimal(20,4)")]
	public System.Nullable<decimal> PrecioUnitario
	{
		get
		{
			return this._PrecioUnitario;
		}
		set
		{
			if ((this._PrecioUnitario != value))
			{
				this._PrecioUnitario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(200)")]
	public string Comentario
	{
		get
		{
			return this._Comentario;
		}
		set
		{
			if ((this._Comentario != value))
			{
				this._Comentario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anulada", DbType="Bit")]
	public System.Nullable<bool> anulada
	{
		get
		{
			return this._anulada;
		}
		set
		{
			if ((this._anulada != value))
			{
				this._anulada = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="VarChar(50)")]
	public string motivo
	{
		get
		{
			return this._motivo;
		}
		set
		{
			if ((this._motivo != value))
			{
				this._motivo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confirmada", DbType="Bit")]
	public System.Nullable<bool> confirmada
	{
		get
		{
			return this._confirmada;
		}
		set
		{
			if ((this._confirmada != value))
			{
				this._confirmada = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_vfc", DbType="Bit")]
	public System.Nullable<bool> tipo_vfc
	{
		get
		{
			return this._tipo_vfc;
		}
		set
		{
			if ((this._tipo_vfc != value))
			{
				this._tipo_vfc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_criticidad", DbType="Int")]
	public System.Nullable<int> criticidad
	{
		get
		{
			return this._criticidad;
		}
		set
		{
			if ((this._criticidad != value))
			{
				this._criticidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs_criticidad", DbType="VarChar(100)")]
	public string obs_criticidad
	{
		get
		{
			return this._obs_criticidad;
		}
		set
		{
			if ((this._obs_criticidad != value))
			{
				this._obs_criticidad = value;
			}
		}
	}
}

public partial class webr_obtiene_cotizacion_consultaResult
{
	
	private System.Nullable<long> _Fila;
	
	private int _numeroSolicitud;
	
	private string _fecha;
	
	private string _marca;
	
	private string _codRepto;
	
	private string _descripcion;
	
	private int _cantidad;
	
	private string _Concesionario;
	
	private string _precio_solicitud;
	
	private string _tipo;
	
	private string _vin;
	
	private string _envio;
	
	private string _sesion;
	
	private string _Dias;
	
	private string _Estado;
	
	private string _Confirmada;
	
	private string _direccionSucursal;
	
	private System.Nullable<bool> _anulada;
	
	private string _comentario;
	
	private string _motivo;
	
	public webr_obtiene_cotizacion_consultaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fila", DbType="BigInt")]
	public System.Nullable<long> Fila
	{
		get
		{
			return this._Fila;
		}
		set
		{
			if ((this._Fila != value))
			{
				this._Fila = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroSolicitud", DbType="Int NOT NULL")]
	public int numeroSolicitud
	{
		get
		{
			return this._numeroSolicitud;
		}
		set
		{
			if ((this._numeroSolicitud != value))
			{
				this._numeroSolicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="VarChar(30)")]
	public string fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this._fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this._marca = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRepto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string codRepto
	{
		get
		{
			return this._codRepto;
		}
		set
		{
			if ((this._codRepto != value))
			{
				this._codRepto = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this._descripcion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
	public int cantidad
	{
		get
		{
			return this._cantidad;
		}
		set
		{
			if ((this._cantidad != value))
			{
				this._cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concesionario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Concesionario
	{
		get
		{
			return this._Concesionario;
		}
		set
		{
			if ((this._Concesionario != value))
			{
				this._Concesionario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_solicitud", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string precio_solicitud
	{
		get
		{
			return this._precio_solicitud;
		}
		set
		{
			if ((this._precio_solicitud != value))
			{
				this._precio_solicitud = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string tipo
	{
		get
		{
			return this._tipo;
		}
		set
		{
			if ((this._tipo != value))
			{
				this._tipo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vin", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string vin
	{
		get
		{
			return this._vin;
		}
		set
		{
			if ((this._vin != value))
			{
				this._vin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string envio
	{
		get
		{
			return this._envio;
		}
		set
		{
			if ((this._envio != value))
			{
				this._envio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string sesion
	{
		get
		{
			return this._sesion;
		}
		set
		{
			if ((this._sesion != value))
			{
				this._sesion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Dias
	{
		get
		{
			return this._Dias;
		}
		set
		{
			if ((this._Dias != value))
			{
				this._Dias = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(5)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmada", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
	public string Confirmada
	{
		get
		{
			return this._Confirmada;
		}
		set
		{
			if ((this._Confirmada != value))
			{
				this._Confirmada = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccionSucursal", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string direccionSucursal
	{
		get
		{
			return this._direccionSucursal;
		}
		set
		{
			if ((this._direccionSucursal != value))
			{
				this._direccionSucursal = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anulada", DbType="Bit")]
	public System.Nullable<bool> anulada
	{
		get
		{
			return this._anulada;
		}
		set
		{
			if ((this._anulada != value))
			{
				this._anulada = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(200)")]
	public string comentario
	{
		get
		{
			return this._comentario;
		}
		set
		{
			if ((this._comentario != value))
			{
				this._comentario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="VarChar(50)")]
	public string motivo
	{
		get
		{
			return this._motivo;
		}
		set
		{
			if ((this._motivo != value))
			{
				this._motivo = value;
			}
		}
	}
}

public partial class webr_valida_estado_cotizacionResult
{
	
	private System.Nullable<bool> _confirmada;
	
	private string _Estado;
	
	public webr_valida_estado_cotizacionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confirmada", DbType="Bit")]
	public System.Nullable<bool> confirmada
	{
		get
		{
			return this._confirmada;
		}
		set
		{
			if ((this._confirmada != value))
			{
				this._confirmada = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(5)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
}
#pragma warning restore 1591
