//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.1.
// 


/// <remarks/>
// CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
// CODEGEN: No se controló el elemento de extensión WSDL opcional 'EndpointReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/08/addressing'.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ZB_CONSUL_PED", Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class ZWS_CONSUL_PED : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback MI_WebS_Consul_Ped_Repues_SynchOperationCompleted;
    
    /// <remarks/>
    public ZWS_CONSUL_PED() {
        this.Url = "http://skerptat.sk.cl:8000/sap/bc/srt/xip/sap/zmi_webs_consul_ped_repues_syn/200/" +
            "zws_consul_ped/zb_consul_ped";
    }
    
    /// <remarks/>
    public event MI_WebS_Consul_Ped_Repues_SynchCompletedEventHandler MI_WebS_Consul_Ped_Repues_SynchCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("MT_ERP_PdoVtas_Consul", Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
    public DT_ERP_PdoVtas_Consul MI_WebS_Consul_Ped_Repues_Synch([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:skb.cl/web-erp:03CrearPedVtas")] DT_Web_PdoVtas_Consul MT_Web_PdoVtas_Consul) {
        object[] results = this.Invoke("MI_WebS_Consul_Ped_Repues_Synch", new object[] {
                    MT_Web_PdoVtas_Consul});
        return ((DT_ERP_PdoVtas_Consul)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMI_WebS_Consul_Ped_Repues_Synch(DT_Web_PdoVtas_Consul MT_Web_PdoVtas_Consul, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MI_WebS_Consul_Ped_Repues_Synch", new object[] {
                    MT_Web_PdoVtas_Consul}, callback, asyncState);
    }
    
    /// <remarks/>
    public DT_ERP_PdoVtas_Consul EndMI_WebS_Consul_Ped_Repues_Synch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DT_ERP_PdoVtas_Consul)(results[0]));
    }
    
    /// <remarks/>
    public void MI_WebS_Consul_Ped_Repues_SynchAsync(DT_Web_PdoVtas_Consul MT_Web_PdoVtas_Consul) {
        this.MI_WebS_Consul_Ped_Repues_SynchAsync(MT_Web_PdoVtas_Consul, null);
    }
    
    /// <remarks/>
    public void MI_WebS_Consul_Ped_Repues_SynchAsync(DT_Web_PdoVtas_Consul MT_Web_PdoVtas_Consul, object userState) {
        if ((this.MI_WebS_Consul_Ped_Repues_SynchOperationCompleted == null)) {
            this.MI_WebS_Consul_Ped_Repues_SynchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_WebS_Consul_Ped_Repues_SynchOperationCompleted);
        }
        this.InvokeAsync("MI_WebS_Consul_Ped_Repues_Synch", new object[] {
                    MT_Web_PdoVtas_Consul}, this.MI_WebS_Consul_Ped_Repues_SynchOperationCompleted, userState);
    }
    
    private void OnMI_WebS_Consul_Ped_Repues_SynchOperationCompleted(object arg) {
        if ((this.MI_WebS_Consul_Ped_Repues_SynchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MI_WebS_Consul_Ped_Repues_SynchCompleted(this, new MI_WebS_Consul_Ped_Repues_SynchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class DT_Web_PdoVtas_Consul {
    
    private DT_Web_PdoVtas_ConsulPedido pedidoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_Web_PdoVtas_ConsulPedido Pedido {
        get {
            return this.pedidoField;
        }
        set {
            this.pedidoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class DT_Web_PdoVtas_ConsulPedido {
    
    private string i_VBELNField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_VBELN {
        get {
            return this.i_VBELNField;
        }
        set {
            this.i_VBELNField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class DT_ERP_PdoVtas_Consul {
    
    private DT_ERP_PdoVtas_ConsulPedido pedidoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_PdoVtas_ConsulPedido Pedido {
        get {
            return this.pedidoField;
        }
        set {
            this.pedidoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class DT_ERP_PdoVtas_ConsulPedido {
    
    private string e_VKORGField;
    
    private string e_VTEXTField;
    
    private string e_VBELNField;
    
    private string e_AUDATField;
    
    private string e_NETWRField;
    
    private string e_KZWI5Field;
    
    private string e_TOTALField;
    
    private DT_ERP_PdoVtas_ConsulPedidoT_POS[] t_POSField;
    
    private DT_ERP_PdoVtas_ConsulPedidoErrores[] erroresField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VKORG {
        get {
            return this.e_VKORGField;
        }
        set {
            this.e_VKORGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VTEXT {
        get {
            return this.e_VTEXTField;
        }
        set {
            this.e_VTEXTField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VBELN {
        get {
            return this.e_VBELNField;
        }
        set {
            this.e_VBELNField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_AUDAT {
        get {
            return this.e_AUDATField;
        }
        set {
            this.e_AUDATField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_NETWR {
        get {
            return this.e_NETWRField;
        }
        set {
            this.e_NETWRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_KZWI5 {
        get {
            return this.e_KZWI5Field;
        }
        set {
            this.e_KZWI5Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_TOTAL {
        get {
            return this.e_TOTALField;
        }
        set {
            this.e_TOTALField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("T_POS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_PdoVtas_ConsulPedidoT_POS[] T_POS {
        get {
            return this.t_POSField;
        }
        set {
            this.t_POSField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Errores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_PdoVtas_ConsulPedidoErrores[] Errores {
        get {
            return this.erroresField;
        }
        set {
            this.erroresField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class DT_ERP_PdoVtas_ConsulPedidoT_POS {
    
    private string mATNRField;
    
    private string aRKTXField;
    
    private string nETPRField;
    
    private string kWMENGField;
    
    private string bMENGField;
    
    private string bMENG2Field;
    
    private string rFMNGField;
    
    private string rFMNG2Field;
    
    private string sTOCKField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MATNR {
        get {
            return this.mATNRField;
        }
        set {
            this.mATNRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ARKTX {
        get {
            return this.aRKTXField;
        }
        set {
            this.aRKTXField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NETPR {
        get {
            return this.nETPRField;
        }
        set {
            this.nETPRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KWMENG {
        get {
            return this.kWMENGField;
        }
        set {
            this.kWMENGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BMENG {
        get {
            return this.bMENGField;
        }
        set {
            this.bMENGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BMENG2 {
        get {
            return this.bMENG2Field;
        }
        set {
            this.bMENG2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RFMNG {
        get {
            return this.rFMNGField;
        }
        set {
            this.rFMNGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RFMNG2 {
        get {
            return this.rFMNG2Field;
        }
        set {
            this.rFMNG2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STOCK {
        get {
            return this.sTOCKField;
        }
        set {
            this.sTOCKField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:03CrearPedVtas")]
public partial class DT_ERP_PdoVtas_ConsulPedidoErrores {
    
    private string e_TYPEField;
    
    private string e_CODEField;
    
    private string e_NUMBERField;
    
    private string e_MESSAGEField;
    
    private string e_LOG_NOField;
    
    private string e_LOG_MSG_NOField;
    
    private string e_MESSAGE_V1Field;
    
    private string e_MESSAGE_V2Field;
    
    private string e_MESSAGE_V3Field;
    
    private string e_MESSAGE_V4Field;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_TYPE {
        get {
            return this.e_TYPEField;
        }
        set {
            this.e_TYPEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_CODE {
        get {
            return this.e_CODEField;
        }
        set {
            this.e_CODEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_NUMBER {
        get {
            return this.e_NUMBERField;
        }
        set {
            this.e_NUMBERField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE {
        get {
            return this.e_MESSAGEField;
        }
        set {
            this.e_MESSAGEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_LOG_NO {
        get {
            return this.e_LOG_NOField;
        }
        set {
            this.e_LOG_NOField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_LOG_MSG_NO {
        get {
            return this.e_LOG_MSG_NOField;
        }
        set {
            this.e_LOG_MSG_NOField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V1 {
        get {
            return this.e_MESSAGE_V1Field;
        }
        set {
            this.e_MESSAGE_V1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V2 {
        get {
            return this.e_MESSAGE_V2Field;
        }
        set {
            this.e_MESSAGE_V2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V3 {
        get {
            return this.e_MESSAGE_V3Field;
        }
        set {
            this.e_MESSAGE_V3Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V4 {
        get {
            return this.e_MESSAGE_V4Field;
        }
        set {
            this.e_MESSAGE_V4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void MI_WebS_Consul_Ped_Repues_SynchCompletedEventHandler(object sender, MI_WebS_Consul_Ped_Repues_SynchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MI_WebS_Consul_Ped_Repues_SynchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MI_WebS_Consul_Ped_Repues_SynchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DT_ERP_PdoVtas_Consul Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DT_ERP_PdoVtas_Consul)(this.results[0]));
        }
    }
}
