//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.1.
// 


/// <remarks/>
// CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
// CODEGEN: No se controló el elemento de extensión WSDL opcional 'EndpointReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/08/addressing'.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ZB_COTIZA_REP", Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class ZWS_COTIZA_REP : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback MI_WebS_Cotizacion_SynchOperationCompleted;
    
    /// <remarks/>
    public ZWS_COTIZA_REP() {
        this.Url = "http://skerptat.sk.cl:8000/sap/bc/srt/xip/sap/zmi_webs_cotizacion_synch/200/zws_c" +
            "otiza_rep/zb_cotiza_rep";
    }
    
    /// <remarks/>
    public event MI_WebS_Cotizacion_SynchCompletedEventHandler MI_WebS_Cotizacion_SynchCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("MT_ERP_Cotizacion", Namespace="urn:skb.cl/web-erp:02Cotizacion")]
    public DT_ERP_Cotizacion MI_WebS_Cotizacion_Synch([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:skb.cl/web-erp:02Cotizacion")] DT_Web_Ingreso_Cotizacion MT_Web_Ingreso_Cotizacion) {
        object[] results = this.Invoke("MI_WebS_Cotizacion_Synch", new object[] {
                    MT_Web_Ingreso_Cotizacion});
        return ((DT_ERP_Cotizacion)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMI_WebS_Cotizacion_Synch(DT_Web_Ingreso_Cotizacion MT_Web_Ingreso_Cotizacion, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MI_WebS_Cotizacion_Synch", new object[] {
                    MT_Web_Ingreso_Cotizacion}, callback, asyncState);
    }
    
    /// <remarks/>
    public DT_ERP_Cotizacion EndMI_WebS_Cotizacion_Synch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DT_ERP_Cotizacion)(results[0]));
    }
    
    /// <remarks/>
    public void MI_WebS_Cotizacion_SynchAsync(DT_Web_Ingreso_Cotizacion MT_Web_Ingreso_Cotizacion) {
        this.MI_WebS_Cotizacion_SynchAsync(MT_Web_Ingreso_Cotizacion, null);
    }
    
    /// <remarks/>
    public void MI_WebS_Cotizacion_SynchAsync(DT_Web_Ingreso_Cotizacion MT_Web_Ingreso_Cotizacion, object userState) {
        if ((this.MI_WebS_Cotizacion_SynchOperationCompleted == null)) {
            this.MI_WebS_Cotizacion_SynchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_WebS_Cotizacion_SynchOperationCompleted);
        }
        this.InvokeAsync("MI_WebS_Cotizacion_Synch", new object[] {
                    MT_Web_Ingreso_Cotizacion}, this.MI_WebS_Cotizacion_SynchOperationCompleted, userState);
    }
    
    private void OnMI_WebS_Cotizacion_SynchOperationCompleted(object arg) {
        if ((this.MI_WebS_Cotizacion_SynchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MI_WebS_Cotizacion_SynchCompleted(this, new MI_WebS_Cotizacion_SynchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class DT_Web_Ingreso_Cotizacion {
    
    private DT_Web_Ingreso_CotizacionItem itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_Web_Ingreso_CotizacionItem Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class DT_Web_Ingreso_CotizacionItem {
    
    private string i_AUARTField;
    
    private string i_VKORGField;
    
    private string i_VTWEGField;
    
    private string i_SPARTField;
    
    private string i_BNDDTField;
    
    private DT_Web_Ingreso_CotizacionItemI_MATERIALES[] i_MATERIALESField;
    
    private string i_KUNNRField;
    
    private string i_KUNNR2Field;
    
    private string i_TEXTOField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_AUART {
        get {
            return this.i_AUARTField;
        }
        set {
            this.i_AUARTField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_VKORG {
        get {
            return this.i_VKORGField;
        }
        set {
            this.i_VKORGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_VTWEG {
        get {
            return this.i_VTWEGField;
        }
        set {
            this.i_VTWEGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_SPART {
        get {
            return this.i_SPARTField;
        }
        set {
            this.i_SPARTField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_BNDDT {
        get {
            return this.i_BNDDTField;
        }
        set {
            this.i_BNDDTField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("I_MATERIALES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_Web_Ingreso_CotizacionItemI_MATERIALES[] I_MATERIALES {
        get {
            return this.i_MATERIALESField;
        }
        set {
            this.i_MATERIALESField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_KUNNR {
        get {
            return this.i_KUNNRField;
        }
        set {
            this.i_KUNNRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_KUNNR2 {
        get {
            return this.i_KUNNR2Field;
        }
        set {
            this.i_KUNNR2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_TEXTO {
        get {
            return this.i_TEXTOField;
        }
        set {
            this.i_TEXTOField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class DT_Web_Ingreso_CotizacionItemI_MATERIALES {
    
    private string i_MATNRField;
    
    private string i_KWMENGField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_MATNR {
        get {
            return this.i_MATNRField;
        }
        set {
            this.i_MATNRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_KWMENG {
        get {
            return this.i_KWMENGField;
        }
        set {
            this.i_KWMENGField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class DT_ERP_Cotizacion {
    
    private DT_ERP_CotizacionItem itemField;
    
    private DT_ERP_CotizacionErrores[] erroresField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_CotizacionItem Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Errores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_CotizacionErrores[] Errores {
        get {
            return this.erroresField;
        }
        set {
            this.erroresField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class DT_ERP_CotizacionItem {
    
    private string e_VBELNField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VBELN {
        get {
            return this.e_VBELNField;
        }
        set {
            this.e_VBELNField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:02Cotizacion")]
public partial class DT_ERP_CotizacionErrores {
    
    private string e_TYPEField;
    
    private string e_CODEField;
    
    private string e_NUMBERField;
    
    private string e_MESSAGEField;
    
    private string e_LOG_NOField;
    
    private string e_LOG_MSG_NOField;
    
    private string e_MESSAGE_V1Field;
    
    private string e_MESSAGE_V2Field;
    
    private string e_MESSAGE_V3Field;
    
    private string e_MESSAGE_V4Field;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_TYPE {
        get {
            return this.e_TYPEField;
        }
        set {
            this.e_TYPEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_CODE {
        get {
            return this.e_CODEField;
        }
        set {
            this.e_CODEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_NUMBER {
        get {
            return this.e_NUMBERField;
        }
        set {
            this.e_NUMBERField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE {
        get {
            return this.e_MESSAGEField;
        }
        set {
            this.e_MESSAGEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_LOG_NO {
        get {
            return this.e_LOG_NOField;
        }
        set {
            this.e_LOG_NOField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_LOG_MSG_NO {
        get {
            return this.e_LOG_MSG_NOField;
        }
        set {
            this.e_LOG_MSG_NOField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V1 {
        get {
            return this.e_MESSAGE_V1Field;
        }
        set {
            this.e_MESSAGE_V1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V2 {
        get {
            return this.e_MESSAGE_V2Field;
        }
        set {
            this.e_MESSAGE_V2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V3 {
        get {
            return this.e_MESSAGE_V3Field;
        }
        set {
            this.e_MESSAGE_V3Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V4 {
        get {
            return this.e_MESSAGE_V4Field;
        }
        set {
            this.e_MESSAGE_V4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void MI_WebS_Cotizacion_SynchCompletedEventHandler(object sender, MI_WebS_Cotizacion_SynchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MI_WebS_Cotizacion_SynchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MI_WebS_Cotizacion_SynchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DT_ERP_Cotizacion Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DT_ERP_Cotizacion)(this.results[0]));
        }
    }
}
