//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.1.
// 


/// <remarks/>
// CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
// CODEGEN: No se controló el elemento de extensión WSDL opcional 'EndpointReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/08/addressing'.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ZB_CONSULTA_REP", Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class ZWS_CONSULTA_REP : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback MI_WebS_Repuestos_SynchOperationCompleted;
    
    /// <remarks/>
    public ZWS_CONSULTA_REP() {
        this.Url = "http://skerptat.sk.cl:8000/sap/bc/srt/xip/sap/zmi_webs_repuestos_synch/200/zws_co" +
            "nsulta_rep/zb_consulta_rep";
    }
    
    /// <remarks/>
    public event MI_WebS_Repuestos_SynchCompletedEventHandler MI_WebS_Repuestos_SynchCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("MT_ERP_Repuestos", Namespace="urn:skb.cl/web-erp:01Consulta")]
    public DT_ERP_Repuestos MI_WebS_Repuestos_Synch([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:skb.cl/web-erp:01Consulta")] DT_Web_Repuestos MT_Web_Repuestos) {
        object[] results = this.Invoke("MI_WebS_Repuestos_Synch", new object[] {
                    MT_Web_Repuestos});
        return ((DT_ERP_Repuestos)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMI_WebS_Repuestos_Synch(DT_Web_Repuestos MT_Web_Repuestos, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MI_WebS_Repuestos_Synch", new object[] {
                    MT_Web_Repuestos}, callback, asyncState);
    }
    
    /// <remarks/>
    public DT_ERP_Repuestos EndMI_WebS_Repuestos_Synch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DT_ERP_Repuestos)(results[0]));
    }
    
    /// <remarks/>
    public void MI_WebS_Repuestos_SynchAsync(DT_Web_Repuestos MT_Web_Repuestos) {
        this.MI_WebS_Repuestos_SynchAsync(MT_Web_Repuestos, null);
    }
    
    /// <remarks/>
    public void MI_WebS_Repuestos_SynchAsync(DT_Web_Repuestos MT_Web_Repuestos, object userState) {
        if ((this.MI_WebS_Repuestos_SynchOperationCompleted == null)) {
            this.MI_WebS_Repuestos_SynchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_WebS_Repuestos_SynchOperationCompleted);
        }
        this.InvokeAsync("MI_WebS_Repuestos_Synch", new object[] {
                    MT_Web_Repuestos}, this.MI_WebS_Repuestos_SynchOperationCompleted, userState);
    }
    
    private void OnMI_WebS_Repuestos_SynchOperationCompleted(object arg) {
        if ((this.MI_WebS_Repuestos_SynchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MI_WebS_Repuestos_SynchCompleted(this, new MI_WebS_Repuestos_SynchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_Web_Repuestos {
    
    private DT_Web_RepuestosItem itemField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_Web_RepuestosItem Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_Web_RepuestosItem {
    
    private string i_VKORGField;
    
    private string i_MFRPNField;
    
    private string i_KWMENGField;
    
    private string i_MAKTXField;
    
    private string i_MVGR4Field;
    
    private string i_VTWEGField;
    
    private string i_KUNNRField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_VKORG {
        get {
            return this.i_VKORGField;
        }
        set {
            this.i_VKORGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_MFRPN {
        get {
            return this.i_MFRPNField;
        }
        set {
            this.i_MFRPNField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_KWMENG {
        get {
            return this.i_KWMENGField;
        }
        set {
            this.i_KWMENGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_MAKTX {
        get {
            return this.i_MAKTXField;
        }
        set {
            this.i_MAKTXField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_MVGR4 {
        get {
            return this.i_MVGR4Field;
        }
        set {
            this.i_MVGR4Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_VTWEG {
        get {
            return this.i_VTWEGField;
        }
        set {
            this.i_VTWEGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string I_KUNNR {
        get {
            return this.i_KUNNRField;
        }
        set {
            this.i_KUNNRField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_ERP_Repuestos {
    
    private DT_ERP_RepuestosItems itemsField;
    
    private DT_ERP_RepuestosT_ZESD002[] t_ZESD002Field;
    
    private DT_ERP_RepuestosT_ZESD003[] t_ZESD003Field;
    
    private DT_ERP_RepuestosErrores[] erroresField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_RepuestosItems Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("T_ZESD002", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_RepuestosT_ZESD002[] T_ZESD002 {
        get {
            return this.t_ZESD002Field;
        }
        set {
            this.t_ZESD002Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("T_ZESD003", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_RepuestosT_ZESD003[] T_ZESD003 {
        get {
            return this.t_ZESD003Field;
        }
        set {
            this.t_ZESD003Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Errores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_ERP_RepuestosErrores[] Errores {
        get {
            return this.erroresField;
        }
        set {
            this.erroresField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_ERP_RepuestosItems {
    
    private string e_VKORGField;
    
    private string e_MFRPNField;
    
    private string e_KWMENGField;
    
    private string e_MAKTXField;
    
    private string e_MVGR4Field;
    
    private string e_VTWEGField;
    
    private string e_KUNNRField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VKORG {
        get {
            return this.e_VKORGField;
        }
        set {
            this.e_VKORGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MFRPN {
        get {
            return this.e_MFRPNField;
        }
        set {
            this.e_MFRPNField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_KWMENG {
        get {
            return this.e_KWMENGField;
        }
        set {
            this.e_KWMENGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MAKTX {
        get {
            return this.e_MAKTXField;
        }
        set {
            this.e_MAKTXField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MVGR4 {
        get {
            return this.e_MVGR4Field;
        }
        set {
            this.e_MVGR4Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_VTWEG {
        get {
            return this.e_VTWEGField;
        }
        set {
            this.e_VTWEGField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_KUNNR {
        get {
            return this.e_KUNNRField;
        }
        set {
            this.e_KUNNRField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_ERP_RepuestosT_ZESD002 {
    
    private string eZ_BEZEIField;
    
    private string eZ_MFRPNField;
    
    private string eZ_MAKTXField;
    
    private string eZ_KONDMField;
    
    private string eZ_COM_QTYField;
    
    private string eZ_KBETR1Field;
    
    private string eZ_KBETR2Field;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_BEZEI {
        get {
            return this.eZ_BEZEIField;
        }
        set {
            this.eZ_BEZEIField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_MFRPN {
        get {
            return this.eZ_MFRPNField;
        }
        set {
            this.eZ_MFRPNField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_MAKTX {
        get {
            return this.eZ_MAKTXField;
        }
        set {
            this.eZ_MAKTXField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_KONDM {
        get {
            return this.eZ_KONDMField;
        }
        set {
            this.eZ_KONDMField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_COM_QTY {
        get {
            return this.eZ_COM_QTYField;
        }
        set {
            this.eZ_COM_QTYField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_KBETR1 {
        get {
            return this.eZ_KBETR1Field;
        }
        set {
            this.eZ_KBETR1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EZ_KBETR2 {
        get {
            return this.eZ_KBETR2Field;
        }
        set {
            this.eZ_KBETR2Field = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_ERP_RepuestosT_ZESD003 {
    
    private string t_MFRPNField;
    
    private string t_MAKTXField;
    
    private string t_INTTYPEField;
    
    private string t_KONDMField;
    
    private string t_KBETR1Field;
    
    private string t_KBETR2Field;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string T_MFRPN {
        get {
            return this.t_MFRPNField;
        }
        set {
            this.t_MFRPNField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string T_MAKTX {
        get {
            return this.t_MAKTXField;
        }
        set {
            this.t_MAKTXField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string T_INTTYPE {
        get {
            return this.t_INTTYPEField;
        }
        set {
            this.t_INTTYPEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string T_KONDM {
        get {
            return this.t_KONDMField;
        }
        set {
            this.t_KONDMField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string T_KBETR1 {
        get {
            return this.t_KBETR1Field;
        }
        set {
            this.t_KBETR1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string T_KBETR2 {
        get {
            return this.t_KBETR2Field;
        }
        set {
            this.t_KBETR2Field = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:skb.cl/web-erp:01Consulta")]
public partial class DT_ERP_RepuestosErrores {
    
    private string e_TYPEField;
    
    private string e_CODEField;
    
    private string e_NUMBERField;
    
    private string e_MESSAGEField;
    
    private string e_LOG_NOField;
    
    private string e_LOG_MSG_NOField;
    
    private string e_MESSAGE_V1Field;
    
    private string e_MESSAGE_V2Field;
    
    private string e_MESSAGE_V3Field;
    
    private string e_MESSAGE_V4Field;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_TYPE {
        get {
            return this.e_TYPEField;
        }
        set {
            this.e_TYPEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_CODE {
        get {
            return this.e_CODEField;
        }
        set {
            this.e_CODEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_NUMBER {
        get {
            return this.e_NUMBERField;
        }
        set {
            this.e_NUMBERField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE {
        get {
            return this.e_MESSAGEField;
        }
        set {
            this.e_MESSAGEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_LOG_NO {
        get {
            return this.e_LOG_NOField;
        }
        set {
            this.e_LOG_NOField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_LOG_MSG_NO {
        get {
            return this.e_LOG_MSG_NOField;
        }
        set {
            this.e_LOG_MSG_NOField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V1 {
        get {
            return this.e_MESSAGE_V1Field;
        }
        set {
            this.e_MESSAGE_V1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V2 {
        get {
            return this.e_MESSAGE_V2Field;
        }
        set {
            this.e_MESSAGE_V2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V3 {
        get {
            return this.e_MESSAGE_V3Field;
        }
        set {
            this.e_MESSAGE_V3Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string E_MESSAGE_V4 {
        get {
            return this.e_MESSAGE_V4Field;
        }
        set {
            this.e_MESSAGE_V4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void MI_WebS_Repuestos_SynchCompletedEventHandler(object sender, MI_WebS_Repuestos_SynchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MI_WebS_Repuestos_SynchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MI_WebS_Repuestos_SynchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DT_ERP_Repuestos Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DT_ERP_Repuestos)(this.results[0]));
        }
    }
}
